format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$package\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$time\
$line_break\
$character"""

add_newline = true
command_timeout = 1000

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

[time]
disabled = false
style = "fg:#a0a9cb"
format = '[ 🕙 $time ]($style)'

[aws]
symbol = ' '
style = 'yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'
